import { getProductImage, IMAGES } from "./images";

export const SAMPLE_CATEGORIES = [
  { name: "Women's Mojari", slug: "womens-mojari", description: "Elegant Mojari crafted for women" },
  { name: "Men's Mojari", slug: "mens-mojari", description: "Heritage Mojari for men" },
  { name: "Wedding Mojari", slug: "wedding-mojari", description: "Bridal & groom wedding Mojari" },
  { name: "Custom Mojari", slug: "custom-mojari", description: "Fully customizable designs" },
  { name: "Royal Collection", slug: "royal-collection", description: "Our most luxurious pieces" },
];

export const SAMPLE_PRODUCTS = [
  {
    title: "Royal Zari Women's Mojari",
    slug: "royal-zari-womens-mojari",
    description:
      "Handcrafted women's Mojari with gold zari embroidery and pearl accents. Inspired by Jaipur palace motifs — perfect for weddings and festive celebrations.",
    price: 2499,
    images: [IMAGES.women.royal],
    category: "Women's Mojari",
    sizes: ["4", "5", "6", "7", "8", "9"],
    colors: ["Maroon", "Gold", "Cream"],
    stock: 25,
    featured: true,
    sku: "WM101",
    customizable: true,
  },
  {
    title: "Bridal Heritage Mojari",
    slug: "bridal-heritage-mojari",
    description:
      "Exquisite bridal Mojari with mirror work and zari for women. A perfect blend of tradition and luxury for your special day.",
    price: 3999,
    images: [IMAGES.women.wedding],
    category: "Wedding Mojari",
    sizes: ["4", "5", "6", "7", "8"],
    colors: ["Maroon", "Gold", "Cream"],
    stock: 15,
    featured: true,
    sku: "WM102",
    customizable: true,
  },
  {
    title: "Everyday Grace Women's Mojari",
    slug: "everyday-grace-womens-mojari",
    description:
      "Soft leather Mojari for everyday elegance. Lightweight, comfortable, and beautifully embroidered for the modern woman.",
    price: 1799,
    images: [IMAGES.women.casual],
    category: "Women's Mojari",
    sizes: ["4", "5", "6", "7", "8", "9"],
    colors: ["Tan", "Pink", "Cream"],
    stock: 40,
    featured: true,
    sku: "WM103",
    customizable: false,
  },
  {
    title: "Maharani Gold Mojari",
    slug: "maharani-gold-mojari",
    description:
      "The crown jewel for her. Rich maroon velvet with intricate gold zari and pearl embellishments — fit for royalty.",
    price: 5499,
    images: [IMAGES.women.royal],
    category: "Royal Collection",
    sizes: ["5", "6", "7", "8"],
    colors: ["Maroon", "Gold"],
    stock: 8,
    featured: true,
    sku: "WM104",
    customizable: true,
  },
  {
    title: "Custom Queen Mojari",
    slug: "custom-queen-mojari",
    description:
      "Fully customizable women's Mojari — choose leather, color, embroidery, and size. Our artisans bring your vision to life.",
    price: 2999,
    images: [IMAGES.customize],
    category: "Custom Mojari",
    sizes: ["4", "5", "6", "7", "8", "9"],
    colors: ["Maroon", "Gold", "Cream", "Pink", "Black"],
    stock: 50,
    featured: true,
    sku: "WM105",
    customizable: true,
  },
  {
    title: "Classic Leather Men's Mojari",
    slug: "classic-leather-mens-mojari",
    description:
      "Timeless brown leather Mojari with hand-stitched detailing for men. Pairs with ethnic and contemporary outfits.",
    price: 2199,
    images: [IMAGES.men.leather],
    category: "Men's Mojari",
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Brown", "Tan"],
    stock: 30,
    featured: true,
    sku: "MM101",
    customizable: false,
  },
  {
    title: "Groom Royal Mojari",
    slug: "groom-royal-mojari",
    description:
      "Regal men's Mojari for grooms and festive wear. Maroon leather with gold thread embroidery and cushioned sole.",
    price: 3499,
    images: [IMAGES.men.wedding],
    category: "Wedding Mojari",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Maroon", "Gold", "Brown"],
    stock: 20,
    featured: true,
    sku: "MM102",
    customizable: true,
  },
  {
    title: "Desert Tan Men's Mojari",
    slug: "desert-tan-mens-mojari",
    description:
      "Everyday men's Mojari in supple tan leather. Minimalist Rajasthani embossing — comfort for long celebrations.",
    price: 1899,
    images: [IMAGES.men.leather],
    category: "Men's Mojari",
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Tan", "Brown", "Olive"],
    stock: 35,
    featured: false,
    sku: "MM103",
    customizable: false,
  },
];
